<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_TransaksiPengguna extends CI_Model
{
    
    public function simpan_transaksi($data)
    {
        $this->db->insert('transaksi_pengguna', $data);
        
    }

    public function simpan_detail_transaksi($data_rinci)
    {
        $this->db->insert('detail_transaksipengguna', $data_rinci);
        
    }

    public function belum_bayar()
    {
        $this->db->select('*');
        $this->db->from('transaksi_pengguna');
        $this->db->where('user_id', $this->session->userdata('user_id'));
       $this->db->where('status_order=0');

        $this->db->order_by('kode_transaksipengguna', 'desc');
        return $this->db->get()->result();    
    }
    public function diproses()
    {
        $this->db->select('*');
        $this->db->from('transaksi_pengguna');
        $this->db->where('user_id', $this->session->userdata('user_id'));
       $this->db->where('status_order=1');
        
        $this->db->order_by('kode_transaksipengguna', 'desc');
        return $this->db->get()->result();    
    }
    public function dikirim()
    {
        $this->db->select('*');
        $this->db->from('transaksi_pengguna');
        $this->db->where('user_id', $this->session->userdata('user_id'));
       $this->db->where('status_order=2');
        
        $this->db->order_by('kode_transaksipengguna', 'desc');
        return $this->db->get()->result();    
    }
    public function selesai()
    {
        $this->db->select('*');
        $this->db->from('transaksi_pengguna');
        $this->db->where('user_id', $this->session->userdata('user_id'));
       $this->db->where('status_order=3');
        
        $this->db->order_by('kode_transaksipengguna', 'desc');
        return $this->db->get()->result();    
    }
    public function detail_pesanan($kode_transaksipengguna)
    {
        $this->db->select('*');
        $this->db->from('transaksi_pengguna');
        $this->db->join('detail_transaksipengguna', 'detail_transaksipengguna.kode_transaksipengguna = transaksi_pengguna.kode_transaksipengguna', 'left');
        $this->db->where('transaksi_pengguna.kode_transaksipengguna', $kode_transaksipengguna);
        return $this->db->get()->row();      
    }
    public function detail_transaksi($kode_transaksipengguna)
    {
        $this->db->select('*');
        $this->db->from('transaksi_pengguna');
        $this->db->join('detail_transaksipengguna', 'detail_transaksipengguna.kode_transaksipengguna = transaksi_pengguna.kode_transaksipengguna', 'left');
        $this->db->join('tb_retail', 'detail_transaksipengguna.id_retail = tb_retail.id_retail', 'left');
        $this->db->join('tb_jeruk', 'tb_retail.id_jeruk = tb_jeruk.id_jeruk', 'left');
        $this->db->where('transaksi_pengguna.kode_transaksipengguna', $kode_transaksipengguna);
        return $this->db->get()->result();      
    }
    public function rekening()
    {
        $this->db->select('*');
        $this->db->from('tb_rekening');
        return $this->db->get()->result();   
    }
    public function upload_bukti_bayar($data)
    {
        $this->db->where('kode_transaksipengguna', $data['kode_transaksipengguna']);
        $this->db->update('transaksi_pengguna', $data);  
    }
    
    public function update_order($data)
    {
        $this->db->where('kode_transaksipengguna', $data['kode_transaksipengguna']);
        $this->db->update('transaksi_pengguna', $data);   
    }

    function get_all_penjualan($id)
    {
        $data = $this->db->select('*');
        $this->db->from('transaksi_pengguna');
        $this->db->join('detail_transaksipengguna', 'detail_transaksipengguna.kode_transaksipengguna = transaksi_pengguna.kode_transaksipengguna', 'left');
        $this->db->join('tb_retail', 'detail_transaksipengguna.id_retail = tb_retail.id_retail', 'left');
        $this->db->join('tb_user', 'tb_retail.user_id = tb_user.user_id', 'left');
        $this->db->join('tb_jeruk', 'tb_retail.id_jeruk = tb_jeruk.id_jeruk', 'left');
        $this->db->where('tb_user.user_id', $id);
        return $this->db->get()->result();   
    }

}

/* End of file Ikan_pemasok_model.php */
/* Location: ./application/models/Ikan_pemasok_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-10-20 09:31:57 */
/* http://harviacode.com */